# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [6]:
city_csv = "output_data/weather_citydata.csv"
city_weather_data = pd.read_csv(city_csv )
city_weather_data

,City,Country,Lat,Lng,Max Temp,Cloudiness,Humidity,Windspeed,Date
0,atuona,pf,-9.80,-139.03,78.33,1.0,76.0,17.52,1.600225e+09
1,grindavik,is,63.84,-22.43,46.40,90.0,87.0,14.99,1.600225e+09
2,mar del plata,ar,-38.00,-57.56,51.01,13.0,70.0,3.36,1.600225e+09
3,flin flon,ca,54.77,-101.86,37.83,60.0,76.0,16.46,1.600225e+09
4,vilhena,br,-12.74,-60.15,74.14,0.0,29.0,2.48,1.600225e+09
...,...,...,...,...,...,...,...,...,...
567,conde,br,-7.26,-34.91,73.40,20.0,94.0,5.82,1.600226e+09
568,lakki marwat,pk,32.61,70.91,92.32,0.0,28.0,5.37,1.600226e+09
569,suntar,ru,62.14,117.63,58.50,78.0,59.0,0.40,1.600226e+09
570,zeya,ru,53.75,127.27,67.42,100.0,57.0,1.79,1.600226e+09
571,unity,ca,52.45,-109.17,44.60,44.0,75.0,8.25,1.600226e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [7]:
gmaps.configure(api_key=g_key)

In [8]:
locations = city_weather_data[["Lat","Lng"]]
humidity_spot = city_weather_data["Humidity"]
# create the mapping figure
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_spot)
#heat_layer = gmaps.heatmap_layer(locations, weights= Humidity)
# add the heatmap layer to the figure
fig.add_layer(heat_layer)

# display the figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [9]:
Ideal_city = city_weather_data.loc[(city_weather_data["Max Temp"] <= 80) & (city_weather_data["Max Temp"]>65) & 
                                  (city_weather_data["Humidity"] < 65) & (city_weather_data["Cloudiness"] < 45) & 
                                  (city_weather_data["Cloudiness"] > 10) & (city_weather_data["Windspeed"] >0)]
Ideal_city

,City,Country,Lat,Lng,Max Temp,Cloudiness,Humidity,Windspeed,Date
14,meadow lake,ca,34.80,-106.54,73.40,40.0,25.0,9.17,1.600225e+09
70,praia da vitoria,pt,38.73,-27.07,66.20,40.0,59.0,18.32,1.600225e+09
72,praxedis guerrero,mx,31.37,-106.02,78.80,20.0,39.0,6.06,1.600225e+09
128,jumla,np,29.27,82.18,68.36,31.0,54.0,2.35,1.600225e+09
246,petauke,zm,-14.24,31.33,66.88,23.0,46.0,4.74,1.600226e+09
318,dalby,au,-27.18,151.27,77.00,42.0,33.0,7.14,1.600226e+09
378,aripuana,br,-9.17,-60.63,74.95,20.0,29.0,1.01,1.600226e+09
429,inverell,au,-29.78,151.12,78.01,11.0,35.0,5.01,1.600226e+09
443,golden,ca,39.76,-105.22,75.20,40.0,16.0,8.05,1.600226e+09

In [10]:
#Ideal_city = city_weather_data.loc[city_weather_data["City"]== "tura"]
#Ideal_city

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [11]:
params = {"radius": 5000, "types": "lodging",
          "key": g_key }

In [12]:
hotel_df = Ideal_city
hotel_df["Hotel Name"] = ""
for index, row in Ideal_city.iterrows(): 


    lat = row["Lat"]
    lng = row["Lng"]
    print(f"Searching within {row['City']}, {row['Country']}...")
    
    params["location"] = f"{lat}, {lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    hotel_name = requests.get(base_url, params=params)
   
    hotel_name = hotel_name.json()
   
    try:
    
        hotel_df.loc[index, "Hotel Name"] = hotel_name["results"][0]["name"]
    
    except(KeyError, IndexError):
        print("Hotel not found. Skipping...")

C:\Users\zorta\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Searching within meadow lake, ca...

C:\Users\zorta\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Searching within praia da vitoria, pt...
Searching within praxedis guerrero, mx...
Searching within jumla, np...
Searching within petauke, zm...
Searching within dalby, au...
Searching within aripuana, br...
Hotel not found. Skipping...
Searching within inverell, au...
Searching within golden, ca...

In [13]:
hotel_df

,City,Country,Lat,Lng,Max Temp,Cloudiness,Humidity,Windspeed,Date,Hotel Name
14,meadow lake,ca,34.80,-106.54,73.40,40.0,25.0,9.17,1.600225e+09,JKL Inc. R.V Park and Storage
70,praia da vitoria,pt,38.73,-27.07,66.20,40.0,59.0,18.32,1.600225e+09,Hotel Branco I
72,praxedis guerrero,mx,31.37,-106.02,78.80,20.0,39.0,6.06,1.600225e+09,CongregaciÃ³n placitas de Otero
128,jumla,np,29.27,82.18,68.36,31.0,54.0,2.35,1.600225e+09,Hotel Sundar Rara Karnali
246,petauke,zm,-14.24,31.33,66.88,23.0,46.0,4.74,1.600226e+09,Newline Lodge
318,dalby,au,-27.18,151.27,77.00,42.0,33.0,7.14,1.600226e+09,Kobbers Motor Inn Dalby
378,aripuana,br,-9.17,-60.63,74.95,20.0,29.0,1.01,1.600226e+09,
429,inverell,au,-29.78,151.12,78.01,11.0,35.0,5.01,1.600226e+09,Sapphire City Motor Inn
443,golden,ca,39.76,-105.22,75.20,40.0,16.0,8.05,1.600226e+09,"The Golden Hotel, Ascend Hotel Collection"

In [14]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]
print(hotel_info)
print(locations)

['\n<dl>\n<dt>Name</dt><dd>JKL Inc. R.V Park and Storage</dd>\n<dt>City</dt><dd>meadow lake</dd>\n<dt>Country</dt><dd>ca</dd>\n</dl>\n', '\n<dl>\n<dt>Name</dt><dd>Hotel Branco I</dd>\n<dt>City</dt><dd>praia da vitoria</dd>\n<dt>Country</dt><dd>pt</dd>\n</dl>\n', '\n<dl>\n<dt>Name</dt><dd>CongregaciÃ³n placitas de Otero</dd>\n<dt>City</dt><dd>praxedis guerrero</dd>\n<dt>Country</dt><dd>mx</dd>\n</dl>\n', '\n<dl>\n<dt>Name</dt><dd>Hotel Sundar Rara Karnali</dd>\n<dt>City</dt><dd>jumla</dd>\n<dt>Country</dt><dd>np</dd>\n</dl>\n', '\n<dl>\n<dt>Name</dt><dd>Newline Lodge</dd>\n<dt>City</dt><dd>petauke</dd>\n<dt>Country</dt><dd>zm</dd>\n</dl>\n', '\n<dl>\n<dt>Name</dt><dd>Kobbers Motor Inn Dalby</dd>\n<dt>City</dt><dd>dalby</dd>\n<dt>Country</dt><dd>au</dd>\n</dl>\n', '\n<dl>\n<dt>Name</dt><dd></dd>\n<dt>City</dt><dd>aripuana</dd>\n<dt>Country</dt><dd>br</dd>\n</dl>\n', '\n<dl>\n<dt>Name</dt><dd>Sapphire City Motor Inn</dd>\n<dt>City</dt><dd>inverell</dd>\n<dt>Country</dt><dd>au</dd>\n</dl>\n', '\n<dl>\n<dt>Name</dt><dd>The Golden Hotel, Ascend Hotel Collection</dd>\n<dt>City</dt><dd>golden</dd>\n<dt>Country</dt><dd>ca</dd>\n</dl>\n']
       Lat     Lng
14   34.80 -106.54
70   38.73  -27.07
72   31.37 -106.02
128  29.27   82.18
246 -14.24   31.33
318 -27.18  151.27
378  -9.17  -60.63
429 -29.78  151.12
443  39.76 -105.22

In [15]:
# Add marker layer ontop of heat map

# create the mapping figure

marker_layer = gmaps.marker_layer(locations,info_box_content =hotel_info)

#heat_layer = gmaps.heatmap_layer(locations, weights= Humidity)
# add the heatmap layer to the figure
fig.add_layer(marker_layer)

# display the figure
fig
  
# Display figure

Figure(layout=FigureLayout(height='420px'))